/* MODULE 7:DEBUGGING REACT APPS

--MODULE INTRODUCTION--
--UNDERSTANDING REACT ERROR MESSAGES--
CODING EXERCISE 13: FIX ERRORS
--ANALYZING CODE FLOW & WARNINGS--
--WORKING WITH BREAKPOINTS--
--USING THE REACT DEVTOOLS--


 */
